

```{r}
library("readxl")

logisticPseudoR2s <- function(LogModel) {
  ## https://rdrr.io/github/cjvanlissa/motley/src/R/RFunctions.R
	dev <- LogModel$deviance
	nullDev <- LogModel$null.deviance
	modelN <- length(LogModel$fitted.values)
	R.l <- 1 - dev / nullDev
	R.cs <- 1- exp ( -(nullDev - dev) / modelN)
	R.n <- R.cs / ( 1 - ( exp (-(nullDev / modelN))))
	cat("Pseudo R^2 for logistic regression\n")
	cat("Hosmer and Lemeshow R^2 ", round(R.l, 3), "\n")
	cat("Cox and Snell R^2 ", round(R.cs, 3), "\n")
	cat("Nagelkerke R^2 ", round(R.n, 3), "\n")
}

RunTests <- function(Formula, data) {
  model.1 <- glm(Formula,family=binomial(link='logit'),data=data)
  print(summary(model.1))
  Alpha<-0.1
  modelChi <- model.1$null.deviance - model.1$deviance
  chidf <- model.1$df.null - model.1$df.residual
  chisq.prob <- 1 - pchisq(modelChi, chidf)
  cat(sprintf("Compare NULL Model and another (NEW) \nχ2(%s)=%.2f, p=%.3f, New model is significant=%s, Alpha=%.2f\n\n", chidf,modelChi,chisq.prob,chisq.prob<Alpha,Alpha))
  logisticPseudoR2s(model.1)
  print("IC for Beta1")
  print(exp(model.1$coefficients))
  print(exp(confint(model.1,level =1-Alpha)))
}

MountAndRun <- function(data, text, Left, Right) {
  print("")
  print(paste(replicate(40, "="), collapse = ""))
  print(text)
  print( paste("Left field:  ",Left) )
  print( paste("Right field: ",Right) )
  data[Left] <-factor( data[[Left]])
  data[Right] <-factor( data[[Right]])
  tab <- xtabs(~data[[Left]] + data[[Right]])
  print(tab)
  if ( length(tab)==4  ){
    FomRQ<-as.formula(data[[Left]] ~ data[[Right]])
    RunTests(FomRQ, data)
  }else{
    print("********************** ERROR - Data is not enough")
  }
}
```



```{r}
# setwd("E:/temp/GephiToolkit/org.gephi.toolkit.demos/")
# system <- list("ArgoUML","Cassandra","Lucene","Hadoop","Ant")
# for (p in system) {
#   DataSet <- read_excel("DataAllW2.xlsx", sheet = p);

#   DataRQ1.1<-DataSet[which(DataSet$Color=="RED" | DataSet$Color=="BLUE"),]
#   MountAndRun(DataRQ1.1, paste("RQ 1.1 - ",p), "Se tem Clone", "Color")

#   DataRQ1.2<-DataSet[which(DataSet$Color=="RED" | DataSet$Color=="GREEN"),]
#   MountAndRun(DataRQ1.2, paste("RQ 1.2 - ",p), "Se tem Clone", "Color")

#   DataRQ2.1<-DataSet[DataSet$Color=="BLUE",]
#   MountAndRun(DataRQ2.1, paste("RQ 2.1 - ",p), "Se tem Clone", "TypeII")

#   DataRQ2.2<-DataSet[DataSet$Color=="GREEN",]
#   MountAndRun(DataRQ2.2, paste("RQ 2.2 - ",p), "Se tem Clone", "TypeII")

#   DataRQ2.3<-DataSet[DataSet$Color=="RED",]
#   MountAndRun(DataRQ2.3, paste("RQ 2.3 - ", p, " - ★ Model based on the intensity of the smell Complex Class") , "Se tem Clone", "TypeII")
#   MountAndRun(DataRQ2.3, paste("RQ 2.3 - ", p, " - ⊘ Model considering the intensity of the smell Large Class"), "Se tem Clone", "TypeIII")
# }
```



```{r}
# Field HasClone:
#                  True
#                  False
# Field smellOccurrence:
#                        1 - onlyLarge
#                        2 - onlyComplex
#                        3 - cooccurrence (Large AND Complex Class)
# Field TypeII / TypeIII: 
#          C1 - ComplexClass at low  level of intensity
#          C2 - ComplexClass at high level of intensity
#          L1 - LargeClass   at low  level of intensity
#          L2 - LargeClass   at high level of intensity

setwd("E:/temp/GephiToolkit/org.gephi.toolkit.demos/")
system <- list("ArgoUML","Cassandra","Lucene","Hadoop","Ant")
for (p in system) {
  DataSet <- read_excel("DataAllW2V2.xlsx", sheet = p);

  DataRQ1.1<-DataSet[which(DataSet$smellOccurrence=="3 - cooccurrence" | DataSet$smellOccurrence=="2 - onlyComplex"),]
  MountAndRun(DataRQ1.1, paste("RQ 1.1 - ",p), "HasClone", "smellOccurrence")

  DataRQ1.2<-DataSet[which(DataSet$smellOccurrence=="3 - cooccurrence" | DataSet$smellOccurrence=="1 - onlyLarge"),]
  MountAndRun(DataRQ1.2, paste("RQ 1.2 - ",p), "HasClone", "smellOccurrence")

  DataRQ2.1<-DataSet[DataSet$smellOccurrence=="2 - onlyComplex",]
  MountAndRun(DataRQ2.1, paste("RQ 2.1 - ",p), "HasClone", "TypeII")

  DataRQ2.2<-DataSet[DataSet$smellOccurrence=="1 - onlyLarge",]
  MountAndRun(DataRQ2.2, paste("RQ 2.2 - ",p), "HasClone", "TypeII")

  DataRQ2.3<-DataSet[DataSet$smellOccurrence=="3 - cooccurrence",]
  MountAndRun(DataRQ2.3, paste("RQ 2.3 - ", p, " - ★ Model based on the intensity of the smell Complex Class") , "HasClone", "TypeII")
  MountAndRun(DataRQ2.3, paste("RQ 2.3 - ", p, " - ⊘ Model considering the intensity of the smell Large Class"), "HasClone", "TypeIII")
}
```